# Generated by Django 6.0.5 on 2026-06-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=50)),
                ('pdate', models.CharField(max_length=50)),
                ('prent', models.IntegerField()),
                ('pdes', models.CharField(max_length=200)),
                ('tid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('eno', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.CharField(max_length=35)),
                ('enum', models.CharField(max_length=15)),
                ('eadd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('created', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('edate', models.CharField(max_length=50)),
                ('eunit', models.CharField(max_length=20)),
                ('eprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gym_admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=50)),
                ('apass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='gym_member',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=50)),
                ('mpass', models.CharField(max_length=50)),
                ('maddress', models.CharField(max_length=150)),
                ('mgender', models.CharField(max_length=100)),
                ('mage', models.CharField(max_length=20)),
                ('mtime', models.CharField(max_length=10)),
                ('mmobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='plan1',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pdes', models.CharField(max_length=200)),
                ('ptime', models.IntegerField()),
                ('eid', models.CharField(max_length=50)),
                ('prent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('tdes', models.CharField(max_length=50)),
                ('tmobile', models.CharField(max_length=15)),
                ('ttime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='trainer1',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('tdes', models.CharField(max_length=50)),
                ('tmobile', models.CharField(max_length=15)),
                ('ttime', models.CharField(max_length=10)),
            ],
        ),
    ]
