
from . import views
from django.urls import path
##  urls of Gym
from django.conf import settings
from django.conf.urls.static import static
urlpatterns=[
    path('show1/',views.show1,name='show1'),
    path('form1/',views.form1,name='form1'),
    path('getform1/',views.getform1,name='getform1'),
    path('disp/',views.disp,name='disp'),
    path('home/',views.home,name='home'),
    path('memberlogin/', views.memberlogin, name='memberlogin'),
    path('memberlogin1/', views.memberlogin1, name='memberlogin1'),
    path('memberforgotpassword/', views.memberforgotpassword, name='memberforgotpassword'),
    path('adminlogin/', views.adminlogin, name='adminlogin'),
    path('adminlogin1/', views.adminlogin1, name='adminlogin1'),
    path('admindashboard/', views.admindashboard, name='admindashboard'),
    path('adminmember/', views.adminmember, name='adminmember'),
    path('adminaddmember/', views.adminaddmember, name='adminaddmember'),
    path('admineditmember/<int:id>/', views.admineditmember, name='admineditmember'),
    path('update_member/<int:id>/', views.update_member, name='update_member'),
    path('admindeletemember/<int:id>/', views.admindeletemember, name='admindeletemember'),
    path('addmember/', views.addmember, name='addmember'),
    path('adminplan/', views.adminplan, name='adminplan'),
    path('adminaddplan/', views.adminaddplan, name='adminaddplan'),
    path('addplan1/', views.addplan1, name='addplan1'),
    path('admintrainers/', views.admintrainers, name='admintrainers'),
    path('adminaddtrainers/', views.adminaddtrainers, name='adminaddtrainers'),
    path('addtrainer/', views.addtrainer, name='addtrainer'),
    path('adminpayment/', views.adminpayment, name='adminpayment'),
    path('adminrecordpayment/', views.adminrecordpayment, name='adminrecordpayment'),
    path('adminattendance/', views.adminattendance, name='adminattendance'),
    path('adminmarkattendance/', views.adminmarkattendance, name='adminmarkattendance'),
    path('adminequipment/', views.adminequipment, name='adminequipment'),
    path('adminaddequipment/', views.adminaddequipment, name='adminaddequipment'),
    path('addequipment/', views.addequipment, name='addequipment'),
    path('adminenquiries/', views.adminenquiries, name='adminenquiries'),
    path('updateenquiry/<int:id>/', views.updateenquiry,name='updateenquiry'),
    path('addenquiry/', views.addenquiry,name='addenquiry'),
    path('adminworkoutplans/', views.adminworkoutplans, name='adminworkoutplans'),
    path('adminaddworkoutplans/', views.adminaddworkoutplans, name='adminaddworkoutplans'),
    path('addworkoutplans/', views.addworkoutplans, name='addworkoutplans'),
    path('adminfeedback/', views.adminfeedback, name='adminfeedback'),
    path('memberdashboard/', views.memberdashboard, name='memberdashboard'),
    path('membereditprofile/', views.membereditprofile, name='membereditprofile'),
    path('updatememberprofile/<int:mid>/', views.updatememberprofile, name='updatememberprofile'),
    path('memberprofile/', views.memberprofile, name='memberprofile'),
    path('memberchangepassword/', views.memberchangepassword, name='memberchangepassword'),
    path('membermembership/', views.membermembership, name='membermembership'),
    path('memberattendance/', views.memberattendance, name='memberattendance'),
    path('memberpayment/', views.memberpayment, name='memberpayment'),
    path('paymentreceipt/<int:bid>/', views.paymentreceipt, name='paymentreceipt'),
    path('memberworkout/', views.memberworkout, name='memberworkout'),
    path('memberbooking/', views.memberbooking, name='memberbooking'),
    path('membertrainer/', views.membertrainer, name='membertrainer'),
    path('memberpay/', views.memberpay, name='memberpay'),
    path('confirmpayment/', views.confirmpayment, name='confirmpayment'),
    path('memberfeedback/', views.memberfeedback,name='memberfeedback'),
    path('addfeedback/', views.addfeedback,name='addfeedback'),
    path("adminlogout/", views.adminlogout, name="adminlogout"),
    path("memberlogout/", views.memberlogout, name="memberlogout"),
]